#!/usr/bin/env python3
"""Triage pass over triage/cases.json to sort and prioritize cases.

It sorts real-world harms systematically: filter out-of-scope ones with a stated
reason, accept the remainder, and rank accepted cases by leverage so high-value
cases are clear. Every score shows its inputs, ensuring that each ranking
transparently displays its underlying metrics. See docs/triage.md.

Usage:
  python3 tools/triage.py            # print the markdown triage report
  python3 tools/triage.py --check    # validate the corpus only (exit 1 on error)
  python3 tools/triage.py --write    # fill the <!--TRIAGE-START-->..<!--END--> region of docs/triage.md
"""
import json, sys, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CASES = ROOT / "triage" / "cases.json"

# Recurring structural failure signatures.
SIGNATURES = {
    "pattern_of_lawful_acts": "harm arises from an aggregate of individually lawful acts",
    "record_absent":          "the act was not recorded contemporaneously",
    "record_destroyed":       "the record was created and subsequently destroyed",
    "access_gated":           "the record exists but access requires permission and is subject to delay",
    "inaction_no_artifact":   "the issue is a non-decision, leaving no official record to challenge",
    "documentary_gate":       "a documentation requirement excludes people from exercising a right",
    "record_single_authored": "the record exists, but its only author is an interested party with no independent corroboration",
}
REQUIRED = ("id", "harm", "lead", "scope", "signature", "reach", "leverage", "status")


def load():
    doc = json.loads(CASES.read_text())
    errs = []
    for c in doc["cases"]:
        for k in REQUIRED:
            if k not in c:
                errs.append(f"{c.get('id','?')}: missing {k}")
        if c.get("scope") == "offstage" and not c.get("offstage_reason"):
            errs.append(f"{c['id']}: offstage case must state offstage_reason")
        if c.get("status") == "covered":
            if c.get("scope") != "onstage":
                errs.append(f"{c['id']}: a covered case is a real process issue; scope must be onstage")
            if not c.get("covered_by"):
                errs.append(f"{c['id']}: covered case must list covered_by scenarios")
            if not c.get("covered_reason"):
                errs.append(f"{c['id']}: covered case must state covered_reason")
        if c.get("scope") == "onstage" and not (1 <= c.get("reach", 0) <= 3 and 1 <= c.get("leverage", 0) <= 3):
            errs.append(f"{c['id']}: onstage reach/leverage must be 1..3")
        for s in c.get("signature", []):
            if s not in SIGNATURES:
                errs.append(f"{c['id']}: unknown signature '{s}'")
    return doc["cases"], errs


def score(c):
    # leverage: estimated shift in the cost of accountability.
    # reach: number of people affected, public resources, or systemic importance.
    return c["reach"] * c["leverage"]


def md(cases):
    onstage = sorted((c for c in cases if c["scope"] == "onstage" and c.get("status") != "covered"),
                     key=lambda c: (-score(c), -c["reach"], c["id"]))
    covered = [c for c in cases if c.get("status") == "covered"]
    offstage = [c for c in cases if c["scope"] == "offstage"]
    out = []
    out.append(f"_Generated by `tools/triage.py` over `triage/cases.json` "
               f"({len(cases)} cases: {len(onstage)} accepted, "
               f"{len(covered)} closed as covered, {len(offstage)} excluded)._\n")

    out.append("### Accepted: ranked by leverage\n")
    out.append("| # | case | score | reach × leverage | signature | status |")
    out.append("|--:|------|:-----:|:----------------:|-----------|--------|")
    for i, c in enumerate(onstage, 1):
        sig = ", ".join(c["signature"]) or "-"
        caveat = " ⚠ legible-not-remedied" if c.get("remedy_caveat") else ""
        st = f"**{c['status']}**" + (f" (`{c['scenario']}`)" if c.get("scenario") else "")
        out.append(f"| {i} | {c['id']}{caveat} | {score(c)} | {c['reach']} × {c['leverage']} | {sig} | {st} |")

    nexts = [c for c in onstage if c["status"] == "candidate"][:3]
    out.append("\n### Recommended to encode next\n")
    out.append("The highest-leverage cases not yet built as scenarios:\n")
    for c in nexts:
        out.append(f"- **{c['id']}** (score {score(c)}): {c['harm']}\n\n  _Lead: {c['lead']}_")

    if covered:
        out.append("\n### Closed as covered: already on the map\n")
        out.append("Real process issues addressed by a verifiable record through scenarios "
                   "already encoded. In bug triage this corresponds to a duplicate status, "
                   "noting the existing cases that cover the issue.\n")
        out.append("| case | covered by | reason |")
        out.append("|------|------------|--------|")
        for c in covered:
            by = ", ".join(f"`{s}`" for s in c["covered_by"])
            out.append(f"| {c['id']} | {by} | {c['covered_reason']} |")

    out.append("\n### Excluded: out of scope\n")
    out.append("Not defects that a checkable record can address; each is closed with an explanatory reason.\n")
    out.append("| case | why excluded |")
    out.append("|------|--------------|")
    for c in offstage:
        out.append(f"| {c['id']} | {c['offstage_reason']} |")
    return "\n".join(out)


def main():
    cases, errs = load()
    if errs:
        print("TRIAGE CORPUS INVALID:", file=sys.stderr)
        for e in errs:
            print("  -", e, file=sys.stderr)
        return 1
    if "--check" in sys.argv:
        print(f"ok  {len(cases)} cases valid")
        return 0
    report = md(cases)
    if "--write" in sys.argv:
        page = ROOT / "docs" / "triage.md"
        new, n = re.subn(r'(<!--TRIAGE-START-->).*?(<!--TRIAGE-END-->)',
                         lambda m: m.group(1) + "\n\n" + report + "\n\n" + m.group(2),
                         page.read_text(), count=1, flags=re.S)
        assert n == 1, "TRIAGE markers not found in docs/triage.md"
        page.write_text(new)
        print(f"docs/triage.md regenerated: {len(cases)} cases")
        return 0
    print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
