#!/usr/bin/env python3
"""Triage pass over triage/cases.json — a SCOUT, not a judge.

It sorts real-world harms the way a software team triages bugs: refuse the
out-of-scope ones (with a stated reason), accept the rest, and rank the
accepted ones by leverage so the highest-value case to encode next is obvious.
It decides nothing. Every score shows its inputs — the same discipline the
kernel demands of a form field ("every demand cites its rule") applied to the
triage itself. See docs/triage.md.

Usage:
  python3 tools/triage.py            # print the markdown triage report
  python3 tools/triage.py --check    # validate the corpus only (exit 1 on error)
  python3 tools/triage.py --write    # fill the <!--TRIAGE-START-->..<!--END--> region of docs/triage.md
"""
import json, sys, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CASES = ROOT / "triage" / "cases.json"

# the recurring structural signatures — the "bug categories" the harness found.
SIGNATURES = {
    "pattern_of_lawful_acts": "wrong lives in an aggregate of individually-lawful acts",
    "record_absent":          "the act was never recorded contemporaneously",
    "record_destroyed":       "the record was made, then destroyed",
    "access_gated":           "the record exists but access is by-permission and slow-walkable",
    "inaction_no_artifact":   "the wrong is a non-decision, which leaves nothing to challenge",
    "documentary_gate":       "a document requirement excludes people from a right",
}
REQUIRED = ("id", "harm", "lead", "scope", "signature", "reach", "leverage", "status")


def load():
    doc = json.loads(CASES.read_text())
    errs = []
    for c in doc["cases"]:
        for k in REQUIRED:
            if k not in c:
                errs.append(f"{c.get('id','?')}: missing {k}")
        if c.get("scope") == "offstage" and not c.get("offstage_reason"):
            errs.append(f"{c['id']}: offstage case must state offstage_reason")
        if c.get("scope") == "onstage" and not (1 <= c.get("reach", 0) <= 3 and 1 <= c.get("leverage", 0) <= 3):
            errs.append(f"{c['id']}: onstage reach/leverage must be 1..3")
        for s in c.get("signature", []):
            if s not in SIGNATURES:
                errs.append(f"{c['id']}: unknown signature '{s}'")
    return doc["cases"], errs


def score(c):
    # leverage: how much a cheap, checkable record would shift the COST of the
    # wrong. reach: people / public money / centrality to democratic function.
    # A break (record destroyable) or a toothless remedy shows up as low leverage,
    # set by the human's reading — the score does not hide it.
    return c["reach"] * c["leverage"]


def md(cases):
    onstage = sorted((c for c in cases if c["scope"] == "onstage"),
                     key=lambda c: (-score(c), -c["reach"], c["id"]))
    offstage = [c for c in cases if c["scope"] == "offstage"]
    out = []
    out.append(f"_Generated by `tools/triage.py` over `triage/cases.json` "
               f"({len(cases)} cases: {len(onstage)} accepted, {len(offstage)} refused)._\n")

    out.append("### Accepted — ranked by leverage\n")
    out.append("| # | case | score | reach × leverage | signature | status |")
    out.append("|--:|------|:-----:|:----------------:|-----------|--------|")
    for i, c in enumerate(onstage, 1):
        sig = ", ".join(c["signature"]) or "—"
        caveat = " ⚠ legible-not-remedied" if c.get("remedy_caveat") else ""
        st = f"**{c['status']}**" + (f" (`{c['scenario']}`)" if c.get("scenario") else "")
        out.append(f"| {i} | {c['id']}{caveat} | {score(c)} | {c['reach']} × {c['leverage']} | {sig} | {st} |")

    nexts = [c for c in onstage if c["status"] == "candidate"][:3]
    out.append("\n### Recommended to encode next\n")
    out.append("The highest-leverage cases not yet built as scenarios:\n")
    for c in nexts:
        out.append(f"- **{c['id']}** (score {score(c)}) — {c['harm']}  \n  _Lead: {c['lead']}_")

    out.append("\n### Refused — out of scope\n")
    out.append("Not defects a checkable record can touch; each is closed with its reason.\n")
    out.append("| case | why refused |")
    out.append("|------|-------------|")
    for c in offstage:
        out.append(f"| {c['id']} | {c['offstage_reason']} |")
    return "\n".join(out)


def main():
    cases, errs = load()
    if errs:
        print("TRIAGE CORPUS INVALID:", file=sys.stderr)
        for e in errs:
            print("  -", e, file=sys.stderr)
        return 1
    if "--check" in sys.argv:
        print(f"ok  {len(cases)} cases valid")
        return 0
    report = md(cases)
    if "--write" in sys.argv:
        page = ROOT / "docs" / "triage.md"
        new, n = re.subn(r'(<!--TRIAGE-START-->).*?(<!--TRIAGE-END-->)',
                         lambda m: m.group(1) + "\n\n" + report + "\n\n" + m.group(2),
                         page.read_text(), count=1, flags=re.S)
        assert n == 1, "TRIAGE markers not found in docs/triage.md"
        page.write_text(new)
        print(f"docs/triage.md regenerated: {len(cases)} cases")
        return 0
    print(report)
    return 0


if __name__ == "__main__":
    sys.exit(main())
